### PR TITLE
added ctrl+r for switching search type...

### PR DESCRIPTION
**Pull request by koreno**
...because WebSlit's xterm emulator doesn't deal with ctrl+/

### CODE REVIEW

**Comment by tigrawap** [comment]
Did you try checking what it emits on ctrl+/? Maybe it can be caught instead

**Comment by koreno** [comment]
Believe me I tried... digging into "Go" code is still out of my comfort zone...
ctrl+/ seems not very standard, especially in the context of a **browser** that is expected to send your keystrokes to a javascript that is attempting to mimic a terminal...

If there was a keyboard mapping configuration file you could do away with all this and let the user customize. For now I have a fork with this piece of code, just thought it would make sense offer it upstream.

**Comment by tigrawap** [comment]
Can you try running this using webssh/hack around webslit to run this instead of slit:
https://github.com/nsf/termbox-go/blob/master/_demos/keyboard.go

To see what it receives when you do ctrl+/ in browser?

**Comment by tigrawap** [comment]
Nevermind, tried webssh directly, it sends nothing

**Pull request merged**
